author: yanm1ng # 作者
description: yanm1ng's blog
keyword: hexo-theme, vuejs
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus

comment: gitment

# gitment config
gitment_owner: yanm1ng
gitment_repo: yanm1ng.github.io
gitment_oauth_id: 0f87e490e00ee3fd87ef
gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 
google_analytics:
# disqus config
disqus_shortname: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://avatars3.githubusercontent.com/u/16443628?v=3&s=460
  description: "The end is always near."
  weibo_username: yanm1ng
  twitter_username: yanm1ng
  github_username: yanm1ng
  zhihu_username: yummy1121
  douban_username: yanm1ng
  linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
